version: '3'
services:
  csharp: #docker run -it -v ${PWD}:/work -w /work -p 5000:5000 kalwar/csharp:1.0.0 /bin/sh
    container_name: csharp
    image: kalwar/csharp:1.0.0
    build: ./c#
    working_dir: /work
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    volumes:
      - ./c#/src/:/work
    ports:
      - 5000:5000
  nodejs: #docker run -it -v ${PWD}:/work -w /work -p 5002:5000 kalwar/nodejs:1.0.0 /bin/sh
    container_name: nodejs
    image: kalwar/nodejs:1.0.0
    build: ./nodejs
    working_dir: /work
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    volumes:
      - ./nodejs/src/:/work
    ports:
      - 5002:5000
